name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: install pre-commit
      run: pipx install pre-commit

    - name: lint
      run: pre-commit run --all --show-diff-on-failure --color=always
